apiVersion: v1
kind: Pod
metadata:
  name: testpod-client
  namespace: default
  labels:
    app: my-app
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0
  containers:
  - name: appcntr1
    image: k8s.gcr.io/e2e-test-images/agnhost:2.21
    args:
      - netexec
      - --http-port=9080
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9080
        name: http
        protocol: TCP
