apiVersion: v1
kind: Pod
metadata:
  name: linux-agnhost
  labels:
    selector-f7ca16fa-92e7-4b03-940d-d45805936379: "true"
spec:
  hostNetwork: true
  containers:
  - name: linux-agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.21
    args:
      - netexec
      - --http-port=8080
      - --udp-port=8081
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      - containerPort: 8081
        name: udp
        protocol: UDP
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/hostname: worker-1
