apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: node-port-service
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 32268
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: udp
      nodePort: 30373
      port: 90
      protocol: UDP
      targetPort: 8081
    selector:
      selector-f7ca16fa-92e7-4b03-940d-d45805936379: "true"
    sessionAffinity: None
    type: NodePort
kind: List
